// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces/forcast_getter.go
//
// Generated by this command:
//
//	mockgen -source=interfaces/forcast_getter.go -destination=interfaces/mocks/forcast_getter.go
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	data "national-weather-service-api/data"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockForcastGetter is a mock of ForcastGetter interface.
type MockForcastGetter struct {
	ctrl     *gomock.Controller
	recorder *MockForcastGetterMockRecorder
}

// MockForcastGetterMockRecorder is the mock recorder for MockForcastGetter.
type MockForcastGetterMockRecorder struct {
	mock *MockForcastGetter
}

// NewMockForcastGetter creates a new mock instance.
func NewMockForcastGetter(ctrl *gomock.Controller) *MockForcastGetter {
	mock := &MockForcastGetter{ctrl: ctrl}
	mock.recorder = &MockForcastGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockForcastGetter) EXPECT() *MockForcastGetterMockRecorder {
	return m.recorder
}

// GetForcast mocks base method.
func (m *MockForcastGetter) GetForcast(lat, long float64) (*data.Forcast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForcast", lat, long)
	ret0, _ := ret[0].(*data.Forcast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForcast indicates an expected call of GetForcast.
func (mr *MockForcastGetterMockRecorder) GetForcast(lat, long any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForcast", reflect.TypeOf((*MockForcastGetter)(nil).GetForcast), lat, long)
}
